# Generated by Django 5.2.7 on 2025-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=200)),
                ('office_date', models.DateField()),
                ('event_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('entry_status', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
